"""System RAG memory store — DuckDB-backed vector store for agent self-evolution.

This store holds system-generated memories that are NOT user-editable:
  - conversation_summary: per-conversation summaries for long-term context
  - archival_memory: Letta-style semantically searchable facts/knowledge
  - skill_evolution: agent self-improvement notes and patterns
  - system_insight: cross-session patterns and operational observations

All entries are auto-generated by the memory pipeline during agent execution.
"""

from __future__ import annotations

import hashlib
import json
import logging
import math
import threading
import time
import uuid
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import duckdb

from src.agents.memory.governance import (
    build_memory_governance_summary,
    is_memory_expired,
    prepare_memory_write,
)
from src.runtime.config.memory_config import get_memory_config
from src.storage.rag import get_unified_rag_store
from src.storage.rag.unified_store import connect_duckdb_with_retry

logger = logging.getLogger(__name__)

_DEFAULT_DB_NAME = "system_memory.duckdb"
ALLOWED_SYSTEM_MEMORY_NAMESPACES = frozenset(
    {
        "conversation_summary",
        "archival_memory",
        "skill_evolution",
        "system_insight",
    }
)
MAX_SYSTEM_MEMORY_SEARCH_TOP_K = 25
MAX_SYSTEM_MEMORY_LIST_LIMIT = 100


def validate_system_memory_namespace(namespace: str) -> str:
    candidate = (namespace or "").strip()
    if candidate not in ALLOWED_SYSTEM_MEMORY_NAMESPACES:
        raise ValueError(f"Unsupported system memory namespace '{namespace}'. Allowed namespaces: {sorted(ALLOWED_SYSTEM_MEMORY_NAMESPACES)}")
    return candidate


def clamp_system_memory_search_top_k(top_k: int) -> int:
    return max(1, min(int(top_k), MAX_SYSTEM_MEMORY_SEARCH_TOP_K))


def clamp_system_memory_list_limit(limit: int) -> int:
    return max(1, min(int(limit), MAX_SYSTEM_MEMORY_LIST_LIMIT))


@dataclass
class SystemMemoryEntry:
    id: str
    namespace: str
    content: str
    metadata: dict[str, Any] = field(default_factory=dict)
    score: float = 0.0


class SystemRAGStore:
    """DuckDB-backed RAG store for system-generated agent memories."""

    def __init__(self, db_path: Path | None = None) -> None:
        self._rag = get_unified_rag_store()
        self._db_path = db_path or self._rag.db_path
        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        self._embedding = self._rag
        # In-process search result cache: {key: (timestamp, results)}
        self._search_cache: dict[str, tuple[float, list[SystemMemoryEntry]]] = {}
        self._search_cache_lock = threading.Lock()
        self._write_gen: dict[str, int] = defaultdict(int)
        self._initialize()

    def _connect(self) -> duckdb.DuckDBPyConnection:
        return connect_duckdb_with_retry(self._db_path)

    def _initialize(self) -> None:
        with self._connect() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS system_memories (
                    id VARCHAR PRIMARY KEY,
                    namespace VARCHAR NOT NULL,
                    content TEXT NOT NULL,
                    metadata_json TEXT,
                    embedding_json TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    agent_name VARCHAR
                )
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_sm_namespace ON system_memories(namespace)")

    # ── Write ────────────────────────────────────────────────────────

    def add(
        self,
        namespace: str,
        content: str,
        *,
        agent_name: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> str:
        """Add a single system memory entry with auto-generated embedding."""
        namespace = validate_system_memory_namespace(namespace)
        configured = get_memory_config()
        governed = prepare_memory_write(
            namespace,
            content,
            agent_name=agent_name,
            metadata=metadata,
            config=configured,
        )
        if configured.write_governance_enabled and not governed.allowed:
            logger.info(
                "SystemRAG: denied write for namespace=%s reason=%s",
                namespace,
                governed.governance.reason,
            )
            return ""

        entry_id = uuid.uuid4().hex[:16]
        self._write_gen[namespace] += 1
        embedding = self._embedding.embed_one(content)
        meta = dict(governed.metadata)
        meta["created_at"] = datetime.now(UTC).isoformat()
        if agent_name:
            meta["agent_name"] = agent_name

        with self._connect() as conn:
            conn.execute(
                """
                INSERT INTO system_memories
                    (id, namespace, content, metadata_json, embedding_json, agent_name)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                [
                    entry_id,
                    namespace,
                    content,
                    json.dumps(meta, ensure_ascii=False),
                    json.dumps(embedding),
                    agent_name,
                ],
            )
        logger.debug("SystemRAG: added entry %s in namespace=%s", entry_id, namespace)
        return entry_id

    def add_batch(
        self,
        namespace: str,
        contents: list[str],
        *,
        agent_name: str | None = None,
    ) -> list[str]:
        """Add multiple entries efficiently."""
        if not contents:
            return []
        namespace = validate_system_memory_namespace(namespace)
        configured = get_memory_config()
        approved_contents: list[str] = []
        approved_metadata: list[dict[str, Any]] = []
        for content in contents:
            governed = prepare_memory_write(
                namespace,
                content,
                agent_name=agent_name,
                metadata=None,
                config=configured,
            )
            if configured.write_governance_enabled and not governed.allowed:
                logger.info(
                    "SystemRAG: skipped batch write for namespace=%s reason=%s",
                    namespace,
                    governed.governance.reason,
                )
                continue
            approved_contents.append(content)
            approved_metadata.append(dict(governed.metadata))

        if not approved_contents:
            return []

        self._write_gen[namespace] += 1
        embeddings = self._embedding.embed(approved_contents)
        now = datetime.now(UTC).isoformat()
        ids: list[str] = []

        with self._connect() as conn:
            for content, embedding, meta in zip(
                approved_contents,
                embeddings,
                approved_metadata,
                strict=False,
            ):
                entry_id = uuid.uuid4().hex[:16]
                meta = dict(meta)
                meta["created_at"] = now
                if agent_name:
                    meta["agent_name"] = agent_name
                conn.execute(
                    """
                    INSERT INTO system_memories
                        (id, namespace, content, metadata_json, embedding_json, agent_name)
                    VALUES (?, ?, ?, ?, ?, ?)
                    """,
                    [
                        entry_id,
                        namespace,
                        content,
                        json.dumps(meta, ensure_ascii=False),
                        json.dumps(embedding),
                        agent_name,
                    ],
                )
                ids.append(entry_id)
        return ids

    # ── Read ─────────────────────────────────────────────────────────

    @staticmethod
    def _decode_metadata(raw_metadata: str | None) -> dict[str, Any]:
        if not raw_metadata:
            return {}
        try:
            payload = json.loads(raw_metadata)
        except json.JSONDecodeError:
            return {}
        return payload if isinstance(payload, dict) else {}

    def _active_scored_entries_from_rows(
        self,
        rows: list[tuple[Any, ...]],
    ) -> list[SystemMemoryEntry]:
        entries: list[SystemMemoryEntry] = []
        for row in rows:
            metadata = self._decode_metadata(row[3])
            if is_memory_expired(metadata):
                continue
            entries.append(
                SystemMemoryEntry(
                    id=row[0],
                    namespace=row[1],
                    content=row[2],
                    metadata=metadata,
                    score=float(row[4]),
                )
            )
        return entries

    def _active_entries_from_rows(
        self,
        rows: list[tuple[Any, ...]],
    ) -> list[SystemMemoryEntry]:
        entries: list[SystemMemoryEntry] = []
        for row in rows:
            metadata = self._decode_metadata(row[3])
            if is_memory_expired(metadata):
                continue
            entries.append(
                SystemMemoryEntry(
                    id=row[0],
                    namespace=row[1],
                    content=row[2],
                    metadata=metadata,
                )
            )
        return entries

    def search(
        self,
        query: str,
        *,
        namespace: str | None = None,
        top_k: int = 10,
    ) -> list[SystemMemoryEntry]:
        """Semantic search across system memories.

        Results are cached in a thread-safe LRU dict (max 200 entries, 5-min TTL)
        to avoid repeated embedding + DuckDB round-trips for identical queries.
        """
        if namespace is not None:
            namespace = validate_system_memory_namespace(namespace)
        top_k = clamp_system_memory_search_top_k(top_k)

        # ── Cache lookup ──────────────────────────────────────────────────
        gen = self._write_gen.get(namespace or "__all__", 0)
        cache_key = hashlib.md5(  # noqa: S324 — non-security, performance cache key
            f"{namespace}:{gen}:{query}:{top_k}".encode()
        ).hexdigest()
        now = time.monotonic()
        with self._search_cache_lock:
            entry = self._search_cache.get(cache_key)
            if entry is not None and (now - entry[0]) < 300:  # 5-min TTL
                return entry[1]
            # Evict oldest if over capacity
            if len(self._search_cache) >= 200:
                oldest_key = min(self._search_cache, key=lambda k: self._search_cache[k][0])
                del self._search_cache[oldest_key]

        # ── Actual search ─────────────────────────────────────────────────
        query_embedding = self._embedding.embed_one(query)
        try:
            results = self._search_native(query_embedding, namespace=namespace, top_k=top_k)
        except Exception:
            logger.debug("Native search unavailable, using Python fallback", exc_info=True)
            results = self._search_python(query_embedding, namespace=namespace, top_k=top_k)

        # ── Cache store ───────────────────────────────────────────────────
        with self._search_cache_lock:
            self._search_cache[cache_key] = (now, results)

        return results

    def _search_native(
        self,
        query_embedding: list[float],
        *,
        namespace: str | None,
        top_k: int,
    ) -> list[SystemMemoryEntry]:
        query_json = json.dumps(query_embedding)
        ns_filter = "AND namespace = ?" if namespace else ""
        params: list[Any] = [query_json]
        if namespace:
            params.append(namespace)
        params.append(top_k)

        with self._connect() as conn:
            rows = conn.execute(
                f"""
                SELECT id, namespace, content, metadata_json,
                       array_cosine_similarity(
                           CAST(embedding_json::JSON AS FLOAT[]),
                           CAST(?::JSON AS FLOAT[])
                       ) AS score
                FROM system_memories
                WHERE embedding_json IS NOT NULL {ns_filter}
                ORDER BY score DESC
                LIMIT ?
                """,
                params,
            ).fetchall()
        return self._active_scored_entries_from_rows(rows)[:top_k]

    def _search_python(
        self,
        query_embedding: list[float],
        *,
        namespace: str | None,
        top_k: int,
    ) -> list[SystemMemoryEntry]:
        ns_filter = "WHERE namespace = ?" if namespace else ""
        params = [namespace] if namespace else []

        with self._connect() as conn:
            rows = conn.execute(
                f"SELECT id, namespace, content, metadata_json, embedding_json FROM system_memories {ns_filter}",
                params,
            ).fetchall()

        results: list[SystemMemoryEntry] = []
        for row in rows:
            if not row[4]:
                continue
            metadata = self._decode_metadata(row[3])
            if is_memory_expired(metadata):
                continue
            embedding = json.loads(row[4])
            score = _cosine_similarity(query_embedding, embedding)
            results.append(
                SystemMemoryEntry(
                    id=row[0],
                    namespace=row[1],
                    content=row[2],
                    metadata=metadata,
                    score=score,
                )
            )
        results.sort(key=lambda e: e.score, reverse=True)
        return results[:top_k]

    def list_entries(
        self,
        *,
        namespace: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[SystemMemoryEntry]:
        if namespace is not None:
            namespace = validate_system_memory_namespace(namespace)
        limit = clamp_system_memory_list_limit(limit)
        ns_filter = "WHERE namespace = ?" if namespace else ""
        params: list[Any] = []
        if namespace:
            params.append(namespace)
        params.extend([limit, offset])

        with self._connect() as conn:
            rows = conn.execute(
                f"""
                SELECT id, namespace, content, metadata_json
                FROM system_memories {ns_filter}
                ORDER BY created_at DESC
                LIMIT ? OFFSET ?
                """,
                params,
            ).fetchall()
        active_entries = self._active_entries_from_rows(rows)
        return active_entries[offset : offset + limit]

    def cleanup_expired(
        self,
        *,
        namespace: str | None = None,
        limit: int | None = None,
    ) -> dict[str, Any]:
        if namespace is not None:
            namespace = validate_system_memory_namespace(namespace)
        if limit is not None:
            limit = max(1, int(limit))

        ns_filter = "WHERE namespace = ?" if namespace else ""
        params = [namespace] if namespace else []
        with self._connect() as conn:
            rows = conn.execute(
                f"SELECT id, namespace, metadata_json FROM system_memories {ns_filter}",
                params,
            ).fetchall()
            expired_rows = [row for row in rows if is_memory_expired(self._decode_metadata(row[2]))]
            if limit is not None:
                expired_rows = expired_rows[:limit]

            deleted_by_namespace: dict[str, int] = {}
            for entry_id, entry_namespace, _ in expired_rows:
                conn.execute("DELETE FROM system_memories WHERE id = ?", [entry_id])
                deleted_by_namespace[entry_namespace] = deleted_by_namespace.get(entry_namespace, 0) + 1
                self._write_gen[entry_namespace] += 1

        return {
            "deleted_count": len(expired_rows),
            "deleted_by_namespace": deleted_by_namespace,
            "namespace": namespace,
        }

    def stats(self) -> dict[str, Any]:
        with self._connect() as conn:
            rows = conn.execute("SELECT namespace, agent_name, metadata_json FROM system_memories").fetchall()
        active_count = 0
        expired_count = 0
        active_agents: set[str] = set()
        active_by_namespace: dict[str, int] = {}
        expired_by_namespace: dict[str, int] = {}
        for namespace, agent_name, metadata_json in rows:
            metadata = self._decode_metadata(metadata_json)
            if is_memory_expired(metadata):
                expired_count += 1
                expired_by_namespace[namespace] = expired_by_namespace.get(namespace, 0) + 1
                continue
            active_count += 1
            if agent_name:
                active_agents.add(str(agent_name))
            active_by_namespace[namespace] = active_by_namespace.get(namespace, 0) + 1
        return {
            "total_entries": active_count,
            "expired_entries": expired_count,
            "namespaces": len(active_by_namespace),
            "agents": len(active_agents),
            "by_namespace": active_by_namespace,
            "by_namespace_expired": expired_by_namespace,
            "embedding_dim": self._embedding.embedding_dim,
            "embedding_backend": self._embedding.embedding_backend,
            "governance": self.governance_summary(),
        }

    def governance_summary(self) -> dict[str, Any]:
        return {
            "read_only": True,
            "allowed_namespaces": sorted(ALLOWED_SYSTEM_MEMORY_NAMESPACES),
            "max_search_top_k": MAX_SYSTEM_MEMORY_SEARCH_TOP_K,
            "max_list_limit": MAX_SYSTEM_MEMORY_LIST_LIMIT,
            **build_memory_governance_summary(),
        }


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b, strict=False))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)


# ── Singleton ────────────────────────────────────────────────────────

_store: SystemRAGStore | None = None


def get_system_rag_store() -> SystemRAGStore:
    """Get the global SystemRAGStore singleton."""
    global _store
    if _store is None:
        _store = SystemRAGStore()
    return _store
