from __future__ import annotations

from fastapi import FastAPI

from src.gateway.routers import (
    agents,
    artifacts,
    auth,
    bootstrap,
    brain,
    browser_runtime,
    capabilities,
    channels,
    distributed_execution,
    evaluation,
    hooks,
    integrations,
    mcp,
    memory,
    metrics,
    models,
    multi_tenant,
    observation,
    optimization_program,
    orchestration,
    plugins,
    public_runtime,
    query_engine,
    reflection,
    research_runtime,
    runtime,
    self_evolution,
    setup,
    skill_evolution,
    skills,
    suggestions,
    system_execution,
    system_update,
    task_workspaces,
    tools_registry,
    transcription,
    uploads,
    ws_events,
)

ROUTERS = [
    auth.router,
    models.router,
    runtime.router,
    bootstrap.router,
    brain.router,
    system_execution.router,
    system_update.router,
    task_workspaces.router,
    observation.router,
    optimization_program.router,
    research_runtime.router,
    plugins.router,
    capabilities.router,
    browser_runtime.router,
    orchestration.router,
    query_engine.router,
    mcp.router,
    hooks.router,
    memory.router,
    skills.router,
    skill_evolution.router,
    artifacts.router,
    uploads.router,
    agents.router,
    suggestions.router,
    channels.router,
    integrations.router,
    transcription.router,
    setup.router,
    tools_registry.router,
    public_runtime.router,
    ws_events.router,
    metrics.router,
    reflection.router,
    self_evolution.router,
    distributed_execution.router,
    multi_tenant.router,
    evaluation.router,
]


def register_routers(app: FastAPI) -> None:
    for router in ROUTERS:
        app.include_router(router)
