"""Shared interface-layer contracts for 3.7.x task workspace surfaces."""

from src.harness.orchestration import (
    BudgetPolicy,
    CompiledTaskGraph,
    OrchestrationCapability,
    PromptStackProfile,
    RuntimeHandoff,
)
from src.interfaces.research import (
    CreateResearchExperimentRequest,
    ResearchArtifactRef,
    ResearchExperiment,
    ResearchExperimentListResponse,
    ResearchExperimentRunResponse,
    ResearchInstructionProgram,
    ResearchProgramListResponse,
    ResearchRuntimeCapability,
    ResearchTrial,
    RunResearchExperimentRequest,
)
from src.storage.query import (
    QueryEngineCapability,
    QueryRuntimeEvent,
    QuerySession,
    QuerySessionSummary,
)
from src.storage.workflow import (
    AgentConversationRef,
    AgentHandle,
    CheckpointRef,
    DeploymentInterface,
    DockerExecutionProfile,
    TaskCard,
    TaskCardEdge,
    TaskCardGraph,
    TaskProgress,
    TaskWorkspace,
    TaskWorkspaceSummary,
)
from src.tools.plugins import (
    PluginCapability,
    PluginCapabilityListResponse,
    PluginInstallRequest,
    PluginManifest,
    PluginManifestListResponse,
    PluginRegistryEntry,
    PluginRegistryResponse,
)
from src.tools.sandbox.browser import (
    BrowserExecutionSession,
    BrowserRuntimeCapability,
    BrowserRuntimeStatusSnapshot,
    BrowserSessionRequest,
)
from src.tools.system_execution import (
    SystemExecutionPermissionPolicy,
    SystemExecutionPermissionRule,
)

__all__ = [
    "AgentConversationRef",
    "AgentHandle",
    "BrowserExecutionSession",
    "BrowserRuntimeCapability",
    "BrowserRuntimeStatusSnapshot",
    "BrowserSessionRequest",
    "BudgetPolicy",
    "CheckpointRef",
    "CompiledTaskGraph",
    "DeploymentInterface",
    "DockerExecutionProfile",
    "OrchestrationCapability",
    "PromptStackProfile",
    "PluginCapability",
    "PluginCapabilityListResponse",
    "PluginInstallRequest",
    "PluginManifest",
    "PluginManifestListResponse",
    "PluginRegistryEntry",
    "PluginRegistryResponse",
    "QueryEngineCapability",
    "QueryRuntimeEvent",
    "QuerySession",
    "QuerySessionSummary",
    "CreateResearchExperimentRequest",
    "ResearchArtifactRef",
    "ResearchExperiment",
    "ResearchExperimentListResponse",
    "ResearchExperimentRunResponse",
    "ResearchInstructionProgram",
    "ResearchProgramListResponse",
    "ResearchRuntimeCapability",
    "ResearchTrial",
    "RunResearchExperimentRequest",
    "RuntimeHandoff",
    "SystemExecutionPermissionPolicy",
    "SystemExecutionPermissionRule",
    "TaskCard",
    "TaskCardEdge",
    "TaskCardGraph",
    "TaskProgress",
    "TaskWorkspace",
    "TaskWorkspaceSummary",
]
