"""Built-in plugin manifest catalog."""

from __future__ import annotations

from .contracts import PluginCommand, PluginManifest


class PluginCatalog:
    """Own built-in plugin manifests."""

    def seed_manifests(self) -> list[PluginManifest]:
        return [
            PluginManifest(
                plugin_id="compound-engineering-review",
                display_name="Compound Engineering Review",
                version="0.1.0",
                description=("Review-oriented engineering workflow plugin with explicit plan, work, review, and compound capture stages."),
                commands=[
                    PluginCommand(command_id="ce:brainstorm", title="Brainstorm", stage="brainstorm", summary="Refine problem framing before technical planning."),
                    PluginCommand(command_id="ce:plan", title="Plan", stage="plan", summary="Produce an implementation plan with risks, interfaces, and sequencing."),
                    PluginCommand(command_id="ce:review", title="Review", stage="review", summary="Run pre-merge review with artifact and policy awareness."),
                ],
                installation_targets=["codex", "claude", "opencode"],
                review_flow=["brainstorm", "plan", "work", "review", "compound"],
            ),
            PluginManifest(
                plugin_id="workspace-runtime-bridge",
                display_name="Workspace Runtime Bridge",
                version="0.1.0",
                description="Bind task-workspace cards to runtime-facing command surfaces and approvals.",
                commands=[
                    PluginCommand(command_id="wrb:bind", title="Bind Runtime", stage="runtime", summary="Attach runtime bindings and policy labels to task cards."),
                    PluginCommand(command_id="wrb:review", title="Review Runtime", stage="review", summary="Review runtime side effects and approval checkpoints before execution."),
                ],
                installation_targets=["octoagent", "codex"],
                review_flow=["plan", "runtime", "review"],
            ),
            PluginManifest(
                plugin_id="agent-rules-skill-pack",
                display_name="Agent Rules Skill Pack",
                version="0.1.0",
                description="Curated engineering rules adapted from agent-rules-books for OctoAgent task planning, review, and code-quality decisions.",
                commands=[PluginCommand(command_id="arb:load-rules", title="Load Agent Rules", stage="plan", summary="Load engineering rules before planning or reviewing a coding task.")],
                installation_targets=["octoagent", "codex", "claude"],
                review_flow=["plan", "work", "review"],
            ),
            PluginManifest(
                plugin_id="goalbuddy-workflow",
                display_name="Goalbuddy Workflow",
                version="0.1.0",
                description="Goal-contract workflow for turning ambiguous user requests into bounded agent tasks with success checks.",
                commands=[PluginCommand(command_id="goal:plan", title="Plan Goal", stage="plan", summary="Create a goal contract, acceptance checks, and recovery path before execution.")],
                installation_targets=["octoagent", "codex"],
                review_flow=["brainstorm", "plan", "work", "review"],
            ),
            PluginManifest(
                plugin_id="content-experiment-workflow",
                display_name="Cheat On Content Workflow",
                version="0.1.0",
                description="Content experiment workflow inspired by cheat-on-content: score, blind-predict, publish, measure, and retro.",
                commands=[PluginCommand(command_id="coc:experiment", title="Run Content Experiment", stage="work", summary="Plan and review a content item as a calibrated experiment.")],
                installation_targets=["octoagent"],
                review_flow=["plan", "work", "review"],
            ),
            PluginManifest(
                plugin_id="diagram-generation-toolkit",
                display_name="Fireworks Tech Graph Toolkit",
                version="0.1.0",
                description="Technical diagram generation workflow for architecture, UML, and agent workflow artifacts.",
                commands=[PluginCommand(command_id="ftg:diagram", title="Generate Diagram Brief", stage="work", summary="Convert a system explanation into a validated SVG/PNG diagram brief.")],
                installation_targets=["octoagent"],
                review_flow=["plan", "work", "review"],
            ),
            PluginManifest(
                plugin_id="html-deck-generator",
                display_name="Beautiful HTML Deck Generator",
                version="0.1.0",
                description="HTML slide template workflow for polished reports, courseware, and project summaries.",
                commands=[PluginCommand(command_id="bht:deck", title="Select Deck Template", stage="work", summary="Choose a deck structure and produce page-level HTML slide guidance.")],
                installation_targets=["octoagent"],
                review_flow=["plan", "work", "review"],
            ),
            PluginManifest(
                plugin_id="ian-handdrawn-ppt",
                display_name="Ian Handdrawn PPT",
                version="0.1.0",
                description="Chinese hand-drawn technical explanation image deck workflow for covers, pages, and contact sheets.",
                commands=[PluginCommand(command_id="ian:blueprint", title="Create Handdrawn PPT Blueprint", stage="work", summary="Create a Chinese hand-drawn PPT-style image blueprint with strict text and quality gates.")],
                installation_targets=["octoagent", "codex"],
                review_flow=["plan", "work", "review"],
            ),
            PluginManifest(
                plugin_id="mirage-vfs-bridge",
                display_name="Mirage VFS Bridge",
                version="0.1.0",
                description="Virtual filesystem bridge concept for exposing task workspaces, artifacts, and long-running context to agents.",
                commands=[PluginCommand(command_id="mirage:vfs-plan", title="Plan VFS Binding", stage="runtime", summary="Map task inputs, artifacts, and memory into a virtual filesystem contract.")],
                installation_targets=["octoagent"],
                review_flow=["plan", "runtime", "review"],
            ),
            PluginManifest(
                plugin_id="peekaboo-vision-mcp",
                display_name="Peekaboo Vision MCP",
                version="0.1.0",
                description="Screen capture and visual QA MCP template with a platform-neutral OctoAgent workflow.",
                commands=[PluginCommand(command_id="peekaboo:capture-plan", title="Plan Vision Capture", stage="runtime", summary="Resolve screen-capture/VQA capability and define visual verification steps.")],
                installation_targets=["octoagent", "mcp"],
                review_flow=["plan", "runtime", "review"],
            ),
            PluginManifest(
                plugin_id="lightseek-smg-gateway",
                display_name="Lightseek SMG Gateway",
                version="0.1.0",
                description="Model gateway integration reference for routing, OpenAI/Anthropic compatibility, MCP, tenancy, and tokenization caching.",
                commands=[PluginCommand(command_id="smg:gateway-plan", title="Plan Gateway Route", stage="runtime", summary="Design a model routing experiment without replacing the stable gateway path.")],
                installation_targets=["octoagent"],
                review_flow=["plan", "runtime", "review"],
            ),
            PluginManifest(
                plugin_id="tokenspeed-model-benchmark",
                display_name="TokenSpeed Model Benchmark",
                version="0.1.0",
                description="LLM inference benchmark workflow for model backend experiments on GPU hosts.",
                commands=[PluginCommand(command_id="tokenspeed:benchmark-plan", title="Plan TokenSpeed Benchmark", stage="runtime", summary="Define a safe benchmark matrix before trying a TokenSpeed runtime.")],
                installation_targets=["octoagent"],
                review_flow=["plan", "runtime", "review"],
            ),
            PluginManifest(
                plugin_id="witr-runtime-diagnostics",
                display_name="WITR Runtime Diagnostics",
                version="0.1.0",
                description="Runtime process explanation workflow for answering why a service or process is running.",
                commands=[PluginCommand(command_id="witr:diagnose", title="Diagnose Runtime", stage="runtime", summary="Collect a process snapshot and explain runtime ownership and next checks.")],
                installation_targets=["octoagent"],
                review_flow=["runtime", "review"],
            ),
            PluginManifest(
                plugin_id="photo-agents-vision-workflow",
                display_name="Photo Agents Vision Workflow",
                version="0.1.0",
                description="Vision-grounded agent workflow with layered memory and self-written skill checkpoints.",
                commands=[PluginCommand(command_id="photo:workflow", title="Run Vision Workflow", stage="work", summary="Plan a visual task with memory layers, observation checks, and skill reuse.")],
                installation_targets=["octoagent"],
                review_flow=["plan", "work", "review"],
            ),
            PluginManifest(
                plugin_id="cloakbrowser-controlled-automation",
                display_name="CloakBrowser Controlled Automation",
                version="0.1.0",
                description="Controlled browser automation template for explicitly authorized web tasks; disabled for bypass-oriented defaults.",
                commands=[PluginCommand(command_id="cloak:browser-plan", title="Plan Controlled Browser Session", stage="runtime", summary="Check authorization, target policy, and fallback browser runtime before automation.")],
                installation_targets=["octoagent"],
                review_flow=["plan", "runtime", "review"],
            ),
            PluginManifest(
                plugin_id="lumibot-research-strategy",
                display_name="Lumibot Research Strategy",
                version="0.1.0",
                description="Backtestable trading-agent workflow integrated for research and paper-trading strategy design only.",
                commands=[PluginCommand(command_id="lumibot:strategy-plan", title="Plan Paper-Trading Strategy", stage="plan", summary="Define data, signal, risk, backtest, and paper-trading gates without live-trading side effects.")],
                installation_targets=["octoagent"],
                review_flow=["plan", "work", "review"],
            ),
        ]
