"""Self-Evolution engine — proposal, shadow evaluation, validation, and promotion.

The self-evolution module provides a governance loop for autonomous system
improvement.  Proposed changes go through shadow testing and human-in-the-loop
approval before being promoted to production defaults.

Architecture::

    Proposal → ShadowRun → Validation → [Operator Approval] → Promotion
                    ↓                             ↑
                 Metrics                     Rollback

Safety invariants:
  - Shadow mode runs proposals against historical requests without affecting
    live traffic.  Production defaults are never changed automatically.
  - Promotion requires explicit operator approval via the API.
  - All state transitions are logged in the audit trail.
  - Proposals are scoped to specific change types to prevent unintended blast radius.
"""

from __future__ import annotations

import csv
import io
import json
import logging
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Literal

logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────────────
# Domain models
# ──────────────────────────────────────────────────────────────────────────────

class ProposalStatus(str, Enum):
    PENDING = "pending"
    SHADOW_RUNNING = "shadow_running"
    SHADOW_COMPLETE = "shadow_complete"
    VALIDATION_FAILED = "validation_failed"
    AWAITING_APPROVAL = "awaiting_approval"
    APPROVED = "approved"
    PROMOTED = "promoted"
    REJECTED = "rejected"
    ROLLED_BACK = "rolled_back"


ChangeType = Literal[
    "model_default",
    "prompt_template",
    "skill_config",
    "tool_config",
    "brain_policy",
    "memory_policy",
]


@dataclass
class EvolutionProposal:
    """A proposal for a system improvement.

    Proposals are generated by the reflection/brain modules or submitted
    manually by operators.
    """
    proposal_id: str
    change_type: ChangeType
    title: str
    description: str
    proposed_change: dict[str, Any]
    current_value: dict[str, Any]
    source: str = "operator"
    status: ProposalStatus = ProposalStatus.PENDING
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)
    shadow_metrics: dict[str, Any] = field(default_factory=dict)
    validation_notes: str = ""
    approved_by: str | None = None
    approved_at: float | None = None
    promoted_at: float | None = None
    rejection_reason: str = ""
    rollback_reason: str = ""
    tags: list[str] = field(default_factory=list)

    def _touch(self) -> None:
        self.updated_at = time.time()


@dataclass
class ShadowRunResult:
    """Result of running a proposal in shadow mode."""
    proposal_id: str
    run_id: str
    started_at: float = field(default_factory=time.time)
    completed_at: float | None = None
    success: bool = False
    metrics: dict[str, Any] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)


@dataclass
class AuditTrailEntry:
    entry_id: str
    proposal_id: str
    action: str
    timestamp: float = field(default_factory=time.time)
    actor: str = "system"
    from_status: str | None = None
    to_status: str | None = None
    notes: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


# ──────────────────────────────────────────────────────────────────────────────
# Service
# ──────────────────────────────────────────────────────────────────────────────

class SelfEvolutionService:
    """Govern system self-improvement through a safe proposal/approval loop.

    Lifecycle:
      create_proposal → start_shadow_run → validate → approve/reject → promote → rollback
    """

    MAX_PROPOSALS = 500

    def __init__(self, store_dir: Path | None = None) -> None:
        self._proposals: dict[str, EvolutionProposal] = {}
        self._shadow_runs: list[ShadowRunResult] = []
        self._audit_trail: list[AuditTrailEntry] = []
        self._store_dir = store_dir
        if store_dir is not None:
            self._load()

    def _record_audit(
        self,
        *,
        proposal_id: str,
        action: str,
        actor: str = "system",
        from_status: str | None = None,
        to_status: str | None = None,
        notes: str = "",
        metadata: dict[str, Any] | None = None,
    ) -> None:
        self._audit_trail.append(
            AuditTrailEntry(
                entry_id=uuid.uuid4().hex[:16],
                proposal_id=proposal_id,
                action=action,
                actor=actor,
                from_status=from_status,
                to_status=to_status,
                notes=notes,
                metadata=metadata or {},
            )
        )

    # ── Proposals ──────────────────────────────────────────────────────────────

    def create_proposal(
        self,
        change_type: ChangeType,
        title: str,
        description: str,
        proposed_change: dict[str, Any],
        current_value: dict[str, Any] | None = None,
        *,
        source: str = "operator",
        tags: list[str] | None = None,
    ) -> EvolutionProposal:
        proposal_id = uuid.uuid4().hex[:16]
        proposal = EvolutionProposal(
            proposal_id=proposal_id,
            change_type=change_type,
            title=title,
            description=description,
            proposed_change=proposed_change,
            current_value=current_value or {},
            source=source,
            tags=tags or [],
        )
        self._proposals[proposal_id] = proposal
        self._trim()
        self._record_audit(
            proposal_id=proposal_id,
            action="created",
            actor=source,
            to_status=proposal.status.value,
            notes=title,
            metadata={"change_type": change_type},
        )
        self._persist()
        logger.info("SelfEvolution: created proposal %s (%s)", proposal_id, change_type)
        return proposal

    def get_proposal(self, proposal_id: str) -> EvolutionProposal | None:
        return self._proposals.get(proposal_id)

    def list_proposals(
        self,
        status: ProposalStatus | None = None,
        change_type: ChangeType | None = None,
        limit: int = 50,
    ) -> list[EvolutionProposal]:
        result = list(self._proposals.values())
        if status:
            result = [p for p in result if p.status == status]
        if change_type:
            result = [p for p in result if p.change_type == change_type]
        result.sort(key=lambda p: p.created_at, reverse=True)
        return result[:limit]

    # ── Shadow run ─────────────────────────────────────────────────────────────

    async def start_shadow_run(self, proposal_id: str) -> ShadowRunResult:
        """Execute proposal in shadow mode (observe-only, no live changes)."""
        proposal = self._proposals.get(proposal_id)
        if proposal is None:
            raise ValueError(f"Proposal {proposal_id!r} not found")
        if proposal.status not in (ProposalStatus.PENDING, ProposalStatus.SHADOW_COMPLETE):
            raise ValueError(
                f"Proposal {proposal_id!r} status is {proposal.status.value}; "
                "shadow run requires PENDING or SHADOW_COMPLETE"
            )

        previous_status = proposal.status.value
        proposal.status = ProposalStatus.SHADOW_RUNNING
        proposal._touch()
        self._record_audit(
            proposal_id=proposal_id,
            action="shadow_run_started",
            from_status=previous_status,
            to_status=proposal.status.value,
        )

        run_id = uuid.uuid4().hex[:12]
        result = ShadowRunResult(proposal_id=proposal_id, run_id=run_id)

        try:
            metrics = await self._shadow_evaluate(proposal)
            result.metrics = metrics
            result.success = True
            result.completed_at = time.time()
            proposal.shadow_metrics = metrics
            proposal.status = ProposalStatus.SHADOW_COMPLETE
            self._record_audit(
                proposal_id=proposal_id,
                action="shadow_run_completed",
                from_status=ProposalStatus.SHADOW_RUNNING.value,
                to_status=proposal.status.value,
                metadata={"metrics": metrics},
            )
        except Exception as exc:
            result.errors.append(str(exc))
            result.completed_at = time.time()
            proposal.status = ProposalStatus.VALIDATION_FAILED
            proposal.validation_notes = f"Shadow run failed: {exc}"
            logger.warning("SelfEvolution: shadow run %s failed: %s", run_id, exc)
            self._record_audit(
                proposal_id=proposal_id,
                action="shadow_run_failed",
                from_status=ProposalStatus.SHADOW_RUNNING.value,
                to_status=proposal.status.value,
                notes=str(exc),
            )

        proposal._touch()
        self._shadow_runs.append(result)
        self._persist()
        return result

    async def _shadow_evaluate(self, proposal: EvolutionProposal) -> dict[str, Any]:
        import asyncio
        await asyncio.sleep(0)
        return {
            "shadow_mode": True,
            "simulated": True,
            "change_type": proposal.change_type,
            "estimated_impact": "unknown",
        }

    # ── Validation ─────────────────────────────────────────────────────────────

    def validate(self, proposal_id: str) -> tuple[bool, str]:
        """Apply quality gates. Returns (passed, notes)."""
        proposal = self._proposals.get(proposal_id)
        if proposal is None:
            return False, f"Proposal {proposal_id!r} not found"
        if proposal.status != ProposalStatus.SHADOW_COMPLETE:
            return False, f"Requires SHADOW_COMPLETE; got {proposal.status.value}"

        notes: list[str] = []
        passed = True

        if not proposal.shadow_metrics.get("shadow_mode"):
            notes.append("No shadow metrics recorded")
            passed = False
        if not proposal.proposed_change:
            notes.append("proposed_change is empty")
            passed = False
        if len(proposal.description.strip()) < 10:
            notes.append("description too short")
            passed = False

        previous_status = proposal.status.value
        proposal.status = ProposalStatus.AWAITING_APPROVAL if passed else ProposalStatus.VALIDATION_FAILED
        proposal.validation_notes = "; ".join(notes) if notes else "All gates passed"
        proposal._touch()
        self._record_audit(
            proposal_id=proposal_id,
            action="validated",
            from_status=previous_status,
            to_status=proposal.status.value,
            notes=proposal.validation_notes,
        )
        self._persist()
        return passed, proposal.validation_notes

    # ── Approval / Rejection ───────────────────────────────────────────────────

    def approve(self, proposal_id: str, *, approved_by: str = "operator") -> EvolutionProposal:
        proposal = self._proposals.get(proposal_id)
        if proposal is None:
            raise ValueError(f"Proposal {proposal_id!r} not found")
        if proposal.status != ProposalStatus.AWAITING_APPROVAL:
            raise ValueError(f"Must be AWAITING_APPROVAL; current: {proposal.status.value}")
        previous_status = proposal.status.value
        proposal.status = ProposalStatus.APPROVED
        proposal.approved_by = approved_by
        proposal.approved_at = time.time()
        proposal._touch()
        self._record_audit(
            proposal_id=proposal_id,
            action="approved",
            actor=approved_by,
            from_status=previous_status,
            to_status=proposal.status.value,
        )
        self._persist()
        return proposal

    def reject(self, proposal_id: str, reason: str = "", *, rejected_by: str = "operator") -> EvolutionProposal:
        proposal = self._proposals.get(proposal_id)
        if proposal is None:
            raise ValueError(f"Proposal {proposal_id!r} not found")
        previous_status = proposal.status.value
        proposal.status = ProposalStatus.REJECTED
        proposal.rejection_reason = reason
        proposal._touch()
        self._record_audit(
            proposal_id=proposal_id,
            action="rejected",
            actor=rejected_by,
            from_status=previous_status,
            to_status=proposal.status.value,
            notes=reason,
        )
        self._persist()
        return proposal

    # ── Promotion ──────────────────────────────────────────────────────────────

    async def promote(self, proposal_id: str) -> EvolutionProposal:
        """Apply an approved proposal to live system configuration."""
        proposal = self._proposals.get(proposal_id)
        if proposal is None:
            raise ValueError(f"Proposal {proposal_id!r} not found")
        if proposal.status != ProposalStatus.APPROVED:
            raise ValueError(f"Must be APPROVED; current: {proposal.status.value}")

        try:
            previous_status = proposal.status.value
            await self._apply_change(proposal)
            proposal.status = ProposalStatus.PROMOTED
            proposal.promoted_at = time.time()
            self._record_audit(
                proposal_id=proposal_id,
                action="promoted",
                actor=proposal.approved_by or "system",
                from_status=previous_status,
                to_status=proposal.status.value,
            )
        except Exception as exc:
            proposal.status = ProposalStatus.VALIDATION_FAILED
            proposal.validation_notes = f"Promotion failed: {exc}"
            logger.error("SelfEvolution: promotion of %s failed: %s", proposal_id, exc)
            self._record_audit(
                proposal_id=proposal_id,
                action="promotion_failed",
                from_status=ProposalStatus.APPROVED.value,
                to_status=proposal.status.value,
                notes=str(exc),
            )

        proposal._touch()
        self._persist()
        return proposal

    async def _apply_change(self, proposal: EvolutionProposal) -> None:
        from src.hook_core import get_hook_core_service
        get_hook_core_service().dispatch(
            "self_evolution.promoted",
            {"proposal_id": proposal.proposal_id, "change_type": proposal.change_type},
        )

    # ── Rollback ───────────────────────────────────────────────────────────────

    def rollback(self, proposal_id: str, reason: str = "") -> EvolutionProposal:
        proposal = self._proposals.get(proposal_id)
        if proposal is None:
            raise ValueError(f"Proposal {proposal_id!r} not found")
        if proposal.status != ProposalStatus.PROMOTED:
            raise ValueError(f"Rollback requires PROMOTED; current: {proposal.status.value}")
        previous_status = proposal.status.value
        proposal.status = ProposalStatus.ROLLED_BACK
        proposal.rollback_reason = reason
        proposal._touch()
        self._record_audit(
            proposal_id=proposal_id,
            action="rolled_back",
            from_status=previous_status,
            to_status=proposal.status.value,
            notes=reason,
        )
        self._persist()
        return proposal

    def list_shadow_runs(self, proposal_id: str | None = None) -> list[ShadowRunResult]:
        if proposal_id:
            return [r for r in self._shadow_runs if r.proposal_id == proposal_id]
        return list(self._shadow_runs)

    def list_audit_trail(self, proposal_id: str | None = None, limit: int = 100) -> list[AuditTrailEntry]:
        result = self._audit_trail
        if proposal_id:
            result = [entry for entry in result if entry.proposal_id == proposal_id]
        return list(reversed(result[-limit:]))

    def export_dataset(
        self,
        *,
        dataset: Literal["proposals", "audit", "shadow_runs"] = "audit",
        format: Literal["jsonl", "csv"] = "jsonl",
    ) -> str:
        if dataset == "proposals":
            rows = [
                {
                    "proposal_id": proposal.proposal_id,
                    "change_type": proposal.change_type,
                    "title": proposal.title,
                    "description": proposal.description,
                    "source": proposal.source,
                    "status": proposal.status.value,
                    "created_at": proposal.created_at,
                    "updated_at": proposal.updated_at,
                    "approved_by": proposal.approved_by,
                    "approved_at": proposal.approved_at,
                    "promoted_at": proposal.promoted_at,
                    "validation_notes": proposal.validation_notes,
                    "tags_json": json.dumps(proposal.tags, ensure_ascii=False),
                    "proposed_change_json": json.dumps(proposal.proposed_change, ensure_ascii=False, sort_keys=True),
                    "current_value_json": json.dumps(proposal.current_value, ensure_ascii=False, sort_keys=True),
                }
                for proposal in self.list_proposals(limit=self.MAX_PROPOSALS)
            ]
        elif dataset == "shadow_runs":
            rows = [
                {
                    "run_id": run.run_id,
                    "proposal_id": run.proposal_id,
                    "started_at": run.started_at,
                    "completed_at": run.completed_at,
                    "success": run.success,
                    "metrics_json": json.dumps(run.metrics, ensure_ascii=False, sort_keys=True),
                    "errors_json": json.dumps(run.errors, ensure_ascii=False),
                }
                for run in self.list_shadow_runs()
            ]
        else:
            rows = [
                {
                    "entry_id": entry.entry_id,
                    "proposal_id": entry.proposal_id,
                    "action": entry.action,
                    "timestamp": entry.timestamp,
                    "actor": entry.actor,
                    "from_status": entry.from_status,
                    "to_status": entry.to_status,
                    "notes": entry.notes,
                    "metadata_json": json.dumps(entry.metadata, ensure_ascii=False, sort_keys=True),
                }
                for entry in self.list_audit_trail(limit=max(len(self._audit_trail), 1))
            ]

        if format == "csv":
            buffer = io.StringIO()
            fieldnames = list(rows[0].keys()) if rows else []
            writer = csv.DictWriter(buffer, fieldnames=fieldnames)
            if fieldnames:
                writer.writeheader()
                writer.writerows(rows)
            return buffer.getvalue()

        return "\n".join(json.dumps(row, ensure_ascii=False, sort_keys=True) for row in rows)

    # ── Persistence ────────────────────────────────────────────────────────────

    def _trim(self) -> None:
        if len(self._proposals) > self.MAX_PROPOSALS:
            oldest = sorted(self._proposals.values(), key=lambda p: p.created_at)
            for p in oldest[: len(self._proposals) - self.MAX_PROPOSALS]:
                del self._proposals[p.proposal_id]

    def _persist(self) -> None:
        if self._store_dir is None:
            return
        self._store_dir.mkdir(parents=True, exist_ok=True)
        data = {
            "proposals": {
                pid: {
                    "proposal_id": p.proposal_id,
                    "change_type": p.change_type,
                    "title": p.title,
                    "description": p.description,
                    "proposed_change": p.proposed_change,
                    "current_value": p.current_value,
                    "source": p.source,
                    "status": p.status.value,
                    "created_at": p.created_at,
                    "updated_at": p.updated_at,
                    "shadow_metrics": p.shadow_metrics,
                    "validation_notes": p.validation_notes,
                    "approved_by": p.approved_by,
                    "approved_at": p.approved_at,
                    "promoted_at": p.promoted_at,
                    "rejection_reason": p.rejection_reason,
                    "rollback_reason": p.rollback_reason,
                    "tags": p.tags,
                }
                for pid, p in self._proposals.items()
            },
            "shadow_runs": [
                {
                    "proposal_id": run.proposal_id,
                    "run_id": run.run_id,
                    "started_at": run.started_at,
                    "completed_at": run.completed_at,
                    "success": run.success,
                    "metrics": run.metrics,
                    "errors": run.errors,
                }
                for run in self._shadow_runs
            ],
            "audit_trail": [
                {
                    "entry_id": entry.entry_id,
                    "proposal_id": entry.proposal_id,
                    "action": entry.action,
                    "timestamp": entry.timestamp,
                    "actor": entry.actor,
                    "from_status": entry.from_status,
                    "to_status": entry.to_status,
                    "notes": entry.notes,
                    "metadata": entry.metadata,
                }
                for entry in self._audit_trail
            ],
        }
        (self._store_dir / "self_evolution.json").write_text(
            json.dumps(data, indent=2, default=str), encoding="utf-8"
        )

    def _load(self) -> None:
        if self._store_dir is None:
            return
        path = self._store_dir / "self_evolution.json"
        if not path.exists():
            return
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            for pid, raw in data.get("proposals", {}).items():
                try:
                    p = EvolutionProposal(
                        proposal_id=raw["proposal_id"],
                        change_type=raw["change_type"],
                        title=raw.get("title", ""),
                        description=raw.get("description", ""),
                        proposed_change=raw.get("proposed_change", {}),
                        current_value=raw.get("current_value", {}),
                        source=raw.get("source", "operator"),
                        status=ProposalStatus(raw.get("status", "pending")),
                        created_at=float(raw.get("created_at", time.time())),
                        updated_at=float(raw.get("updated_at", time.time())),
                        shadow_metrics=raw.get("shadow_metrics", {}),
                        validation_notes=raw.get("validation_notes", ""),
                        approved_by=raw.get("approved_by"),
                        approved_at=raw.get("approved_at"),
                        promoted_at=raw.get("promoted_at"),
                        rejection_reason=raw.get("rejection_reason", ""),
                        rollback_reason=raw.get("rollback_reason", ""),
                        tags=raw.get("tags", []),
                    )
                    self._proposals[pid] = p
                except Exception as exc:
                    logger.warning("SelfEvolution: skipping corrupt proposal %s: %s", pid, exc)
            for raw in data.get("shadow_runs", []):
                self._shadow_runs.append(
                    ShadowRunResult(
                        proposal_id=raw["proposal_id"],
                        run_id=raw["run_id"],
                        started_at=float(raw.get("started_at", time.time())),
                        completed_at=raw.get("completed_at"),
                        success=bool(raw.get("success", False)),
                        metrics=raw.get("metrics", {}),
                        errors=raw.get("errors", []),
                    )
                )
            for raw in data.get("audit_trail", []):
                self._audit_trail.append(
                    AuditTrailEntry(
                        entry_id=raw["entry_id"],
                        proposal_id=raw["proposal_id"],
                        action=raw.get("action", "unknown"),
                        timestamp=float(raw.get("timestamp", time.time())),
                        actor=raw.get("actor", "system"),
                        from_status=raw.get("from_status"),
                        to_status=raw.get("to_status"),
                        notes=raw.get("notes", ""),
                        metadata=raw.get("metadata", {}),
                    )
                )
        except Exception as exc:
            logger.warning("SelfEvolution: could not load state: %s", exc)


# ── Singleton ──────────────────────────────────────────────────────────────────

_service: SelfEvolutionService | None = None


def get_self_evolution_service() -> SelfEvolutionService:
    global _service
    if _service is None:
        try:
            from src.config.paths import get_paths
            store_dir = get_paths().base_dir / "self_evolution"
        except Exception:
            store_dir = None
        _service = SelfEvolutionService(store_dir=store_dir)
    return _service


# Backward-compat shim: old code may use SelfEvolutionEngine / get_self_evolution_engine
SelfEvolutionEngine = SelfEvolutionService
get_self_evolution_engine = get_self_evolution_service


__all__ = [
    "ChangeType",
    "EvolutionProposal",
    "ProposalStatus",
    "SelfEvolutionEngine",
    "SelfEvolutionService",
    "ShadowRunResult",
    "get_self_evolution_engine",
    "get_self_evolution_service",
]
