#!/usr/bin/env bash

# Shared local/runtime port baseline for OctoAgent.
# Source this file from local scripts before starting services.

: "${OCTO_LANGGRAPH_PORT:=19884}"
: "${OCTO_FRONTEND_PORT:=19886}"
: "${OCTO_GATEWAY_PORT:=19882}"
: "${OCTO_PROVISIONER_PORT:=19888}"
: "${OCTO_NGINX_PORT:=19880}"
: "${OCTO_PUBLIC_BASE_URL:=http://127.0.0.1:${OCTO_NGINX_PORT}}"
: "${OCTO_SANDBOX_BASE_PORT:=19900}"

export OCTO_LANGGRAPH_PORT
export OCTO_FRONTEND_PORT
export OCTO_GATEWAY_PORT
export OCTO_PROVISIONER_PORT
export OCTO_NGINX_PORT
export OCTO_PUBLIC_BASE_URL
export OCTO_SANDBOX_BASE_PORT

export LANGGRAPH_PORT="${LANGGRAPH_PORT:-$OCTO_LANGGRAPH_PORT}"
export FRONTEND_PORT="${FRONTEND_PORT:-$OCTO_FRONTEND_PORT}"
export GATEWAY_PORT="${GATEWAY_PORT:-$OCTO_GATEWAY_PORT}"
export PROVISIONER_PORT="${PROVISIONER_PORT:-$OCTO_PROVISIONER_PORT}"
export NGINX_PORT="${NGINX_PORT:-$OCTO_NGINX_PORT}"

export NEXT_PUBLIC_LOCAL_LANGGRAPH_PORT="${NEXT_PUBLIC_LOCAL_LANGGRAPH_PORT:-$LANGGRAPH_PORT}"
export NEXT_PUBLIC_LOCAL_FRONTEND_PORT="${NEXT_PUBLIC_LOCAL_FRONTEND_PORT:-$FRONTEND_PORT}"
export NEXT_PUBLIC_LOCAL_GATEWAY_PORT="${NEXT_PUBLIC_LOCAL_GATEWAY_PORT:-$GATEWAY_PORT}"
export NEXT_PUBLIC_LOCAL_INGRESS_PORT="${NEXT_PUBLIC_LOCAL_INGRESS_PORT:-$NGINX_PORT}"

export BETTER_AUTH_BASE_URL="${BETTER_AUTH_BASE_URL:-$OCTO_PUBLIC_BASE_URL}"