from .contracts import (
    AgentConversationRef,
    AgentHandle,
    BrowserExecutionSession,
    BrowserRuntimeCapability,
    BrowserRuntimeStatusSnapshot,
    BrowserSessionRequest,
    BudgetPolicy,
    CheckpointRef,
    CompiledTaskGraph,
    CreateResearchExperimentRequest,
    DeploymentInterface,
    DockerExecutionProfile,
    OrchestrationCapability,
    PluginCapability,
    PluginCapabilityListResponse,
    PluginInstallRequest,
    PluginManifest,
    PluginManifestListResponse,
    PluginRegistryEntry,
    PluginRegistryResponse,
    PromptStackProfile,
    QueryEngineCapability,
    QueryRuntimeEvent,
    QuerySession,
    QuerySessionSummary,
    ResearchArtifactRef,
    ResearchExperiment,
    ResearchExperimentListResponse,
    ResearchExperimentRunResponse,
    ResearchInstructionProgram,
    ResearchProgramListResponse,
    ResearchRuntimeCapability,
    ResearchTrial,
    RunResearchExperimentRequest,
    RuntimeHandoff,
    SystemExecutionPermissionPolicy,
    SystemExecutionPermissionRule,
    TaskCard,
    TaskCardEdge,
    TaskCardGraph,
    TaskProgress,
    TaskWorkspace,
    TaskWorkspaceSummary,
)

__all__ = [
    "AgentConversationRef",
    "AgentHandle",
    "BrowserExecutionSession",
    "BrowserRuntimeCapability",
    "BrowserRuntimeStatusSnapshot",
    "BrowserSessionRequest",
    "BudgetPolicy",
    "CheckpointRef",
    "CompiledTaskGraph",
    "DeploymentInterface",
    "DockerExecutionProfile",
    "OrchestrationCapability",
    "PromptStackProfile",
    "PluginCapability",
    "PluginCapabilityListResponse",
    "PluginInstallRequest",
    "PluginManifest",
    "PluginManifestListResponse",
    "PluginRegistryEntry",
    "PluginRegistryResponse",
    "QueryEngineCapability",
    "QueryRuntimeEvent",
    "QuerySession",
    "QuerySessionSummary",
    "CreateResearchExperimentRequest",
    "ResearchArtifactRef",
    "ResearchExperiment",
    "ResearchExperimentListResponse",
    "ResearchExperimentRunResponse",
    "ResearchInstructionProgram",
    "ResearchProgramListResponse",
    "ResearchRuntimeCapability",
    "ResearchTrial",
    "RunResearchExperimentRequest",
    "RuntimeHandoff",
    "SystemExecutionPermissionPolicy",
    "SystemExecutionPermissionRule",
    "TaskCard",
    "TaskCardEdge",
    "TaskCardGraph",
    "TaskProgress",
    "TaskWorkspace",
    "TaskWorkspaceSummary",
    "InterfaceLayerService",
    "get_interface_layer_service",
]

# Lazy import to avoid circular dependency chains
def get_interface_layer_service():
    from .service import get_interface_layer_service as _get
    return _get()

def __getattr__(name):
    if name == "InterfaceLayerService":
        from .service import InterfaceLayerService
        return InterfaceLayerService
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
