"""Hot-load dynamic tools generated by self-evolution proposals (Sprint-3).

We must not touch ``self_evolution/__init__.py`` (APPEND-ONLY policy), so this
module subscribes to the ``self_evolution.promoted`` hook fired by the
facade's ``_apply_change`` and materialises ``change_type='new_tool'``
proposals into Python modules under ``backend/src/tools/builtins/dynamic/``.

Each generated module exposes a ``TOOL`` symbol of type ``BaseTool``. The
``ToolCatalog`` consults ``dynamic.list_dynamic_tools()`` on each load so a
restart is not required — but a registered hook listener also live-reloads
the module immediately after promotion.
"""

from __future__ import annotations

import importlib
import importlib.util
import logging
import sys
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_DYNAMIC_ROOT = Path(__file__).resolve().parents[3] / "src" / "tools" / "builtins" / "dynamic"
_DYNAMIC_ROOT.mkdir(parents=True, exist_ok=True)
(_DYNAMIC_ROOT / "__init__.py").touch(exist_ok=True)


def _module_path(name: str) -> Path:
    safe = "".join(c if c.isalnum() or c == "_" else "_" for c in name).lower()
    return _DYNAMIC_ROOT / f"{safe}.py"


def materialise_tool(*, name: str, source_code: str) -> Path:
    """Write a Python source file under dynamic/ and import it.

    The caller is responsible for review/sandboxing; this function only
    handles file IO and module loading. It refuses overwrite to keep audit
    trails clean — the facade should bump the version suffix instead.
    """
    safe = "".join(c if c.isalnum() or c == "_" else "_" for c in name).lower()
    target = _module_path(safe)
    if target.exists():
        raise FileExistsError(f"Dynamic tool '{safe}' already exists at {target}")
    target.write_text(source_code, encoding="utf-8")
    spec = importlib.util.spec_from_file_location(f"src.tools.builtins.dynamic.{safe}", str(target))
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Failed to build spec for {target}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    if not hasattr(module, "TOOL"):
        raise AttributeError(f"Dynamic tool '{safe}' must export a TOOL symbol")
    logger.info("Dynamic tool '%s' materialised at %s", safe, target)
    return target


def list_dynamic_tools() -> list[Any]:
    """Return all loaded dynamic tools (best-effort, ignores broken modules)."""
    tools: list[Any] = []
    for py in sorted(_DYNAMIC_ROOT.glob("*.py")):
        if py.name == "__init__.py":
            continue
        mod_name = f"src.tools.builtins.dynamic.{py.stem}"
        try:
            mod = sys.modules.get(mod_name) or importlib.import_module(mod_name)
            if hasattr(mod, "TOOL"):
                tools.append(mod.TOOL)
        except Exception as exc:
            logger.warning("Dynamic tool '%s' failed to load: %s", py.stem, exc)
    return tools


def register_hook_listener() -> None:
    """Subscribe to the ``self_evolution.promoted`` hook (Sprint-3)."""
    try:
        from src.harness.hook_core import get_hook_core_service

        svc = get_hook_core_service()
    except Exception as exc:
        logger.debug("Dynamic-tools hook listener skipped: %s", exc)
        return

    def _on_promoted(payload: dict[str, Any]) -> None:
        change_type = payload.get("change_type")
        if change_type != "new_tool":
            return
        name = payload.get("tool_name")
        source = payload.get("source_code")
        if not name or not source:
            logger.warning("new_tool promotion missing name/source_code: %s", payload)
            return
        try:
            materialise_tool(name=str(name), source_code=str(source))
        except Exception as exc:
            logger.warning("new_tool materialisation failed: %s", exc)

    register = getattr(svc, "register_listener", None) or getattr(svc, "subscribe", None)
    if callable(register):
        try:
            register("self_evolution.promoted", _on_promoted)
            logger.info("Dynamic-tools hook listener registered")
        except Exception as exc:
            logger.debug("Could not register hook listener: %s", exc)


__all__ = ["materialise_tool", "list_dynamic_tools", "register_hook_listener"]
