"""Self-evolution domain models (extracted from __init__.py 2026-05-14).

Keeping these dataclasses in their own module makes them importable without
loading the full ``SelfEvolutionService`` (which pulls in the configuration
layer and other heavy dependencies).
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Literal


class ProposalStatus(str, Enum):
    PENDING = "pending"
    SHADOW_RUNNING = "shadow_running"
    SHADOW_COMPLETE = "shadow_complete"
    VALIDATION_FAILED = "validation_failed"
    AWAITING_APPROVAL = "awaiting_approval"
    APPROVED = "approved"
    PROMOTED = "promoted"
    REJECTED = "rejected"
    ROLLED_BACK = "rolled_back"


ChangeType = Literal[
    "model_default",
    "prompt_template",
    "skill_config",
    "tool_config",
    "brain_policy",
    "memory_policy",
]


@dataclass
class EvolutionProposal:
    """A proposal for a system improvement.

    Proposals are generated by the reflection/brain modules or submitted
    manually by operators.
    """

    proposal_id: str
    change_type: ChangeType
    title: str
    description: str
    proposed_change: dict[str, Any]
    current_value: dict[str, Any]
    source: str = "operator"
    status: ProposalStatus = ProposalStatus.PENDING
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)
    shadow_metrics: dict[str, Any] = field(default_factory=dict)
    validation_notes: str = ""
    approved_by: str | None = None
    approved_at: float | None = None
    promoted_at: float | None = None
    rejection_reason: str = ""
    rollback_reason: str = ""
    tags: list[str] = field(default_factory=list)

    def _touch(self) -> None:
        self.updated_at = time.time()


@dataclass
class ShadowRunResult:
    """Result of running a proposal in shadow mode."""

    proposal_id: str
    run_id: str
    started_at: float = field(default_factory=time.time)
    completed_at: float | None = None
    success: bool = False
    metrics: dict[str, Any] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)


@dataclass
class AuditTrailEntry:
    entry_id: str
    proposal_id: str
    action: str
    timestamp: float = field(default_factory=time.time)
    actor: str = "system"
    from_status: str | None = None
    to_status: str | None = None
    notes: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


__all__ = [
    "ProposalStatus",
    "ChangeType",
    "EvolutionProposal",
    "ShadowRunResult",
    "AuditTrailEntry",
]
