import asyncio
import logging
import mimetypes
import os
import zipfile
from pathlib import Path
from urllib.parse import quote

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, PlainTextResponse, Response

from src.gateway.path_utils import resolve_thread_virtual_path

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["artifacts"])


def is_text_file_by_content(path: Path, sample_size: int = 8192) -> bool:
    """Check if file is text by examining content for null bytes."""
    try:
        with open(path, "rb") as f:
            chunk = f.read(sample_size)
            # Text files shouldn't contain null bytes
            return b"\x00" not in chunk
    except Exception:
        return False


def _extract_file_from_skill_archive(zip_path: Path, internal_path: str) -> bytes | None:
    """Extract a file from a .skill ZIP archive.

    Args:
        zip_path: Path to the .skill file (ZIP archive).
        internal_path: Path to the file inside the archive (e.g., "SKILL.md").

    Returns:
        The file content as bytes, or None if not found.
    """
    if not zipfile.is_zipfile(zip_path):
        return None

    try:
        with zipfile.ZipFile(zip_path, "r") as zip_ref:
            # List all files in the archive
            namelist = zip_ref.namelist()

            # Try direct path first
            if internal_path in namelist:
                return zip_ref.read(internal_path)

            # Try with any top-level directory prefix (e.g., "skill-name/SKILL.md")
            for name in namelist:
                if name.endswith("/" + internal_path) or name == internal_path:
                    return zip_ref.read(name)

            # Not found
            return None
    except (zipfile.BadZipFile, KeyError):
        return None


@router.get(
    "/threads/{thread_id}/artifacts/{path:path}",
    summary="Get Artifact File",
    description="Retrieve an artifact file generated by the AI agent. Supports text, HTML, and binary files.",
)
async def get_artifact(thread_id: str, path: str, request: Request) -> FileResponse:
    """Get an artifact file by its path.

    The endpoint automatically detects file types and returns appropriate content types.
    Use the `?download=true` query parameter to force file download.

    Args:
        thread_id: The thread ID.
        path: The artifact path with virtual prefix (e.g., mnt/user-data/outputs/file.txt).
        request: FastAPI request object (automatically injected).

    Returns:
        The file content as a FileResponse with appropriate content type:
        - HTML files: Rendered as HTML
        - Text files: Plain text with proper MIME type
        - Binary files: Inline display with download option

    Raises:
        HTTPException:
            - 400 if path is invalid or not a file
            - 403 if access denied (path traversal detected)
            - 404 if file not found

    Query Parameters:
        download (bool): If true, returns file as attachment for download

    Example:
        - Get HTML file: `/api/threads/abc123/artifacts/mnt/user-data/outputs/index.html`
        - Download file: `/api/threads/abc123/artifacts/mnt/user-data/outputs/data.csv?download=true`
    """
    # Check if this is a request for a file inside a .skill archive (e.g., xxx.skill/SKILL.md)
    if ".skill/" in path:
        # Split the path at ".skill/" to get the ZIP file path and internal path
        skill_marker = ".skill/"
        marker_pos = path.find(skill_marker)
        skill_file_path = path[: marker_pos + len(".skill")]  # e.g., "mnt/user-data/outputs/my-skill.skill"
        internal_path = path[marker_pos + len(skill_marker) :]  # e.g., "SKILL.md"

        actual_skill_path = resolve_thread_virtual_path(thread_id, skill_file_path)

        if not actual_skill_path.exists():
            raise HTTPException(status_code=404, detail=f"Skill file not found: {skill_file_path}")

        if not actual_skill_path.is_file():
            raise HTTPException(status_code=400, detail=f"Path is not a file: {skill_file_path}")

        # Extract the file from the .skill archive
        content = _extract_file_from_skill_archive(actual_skill_path, internal_path)
        if content is None:
            raise HTTPException(status_code=404, detail=f"File '{internal_path}' not found in skill archive")

        # Determine MIME type based on the internal file
        mime_type, _ = mimetypes.guess_type(internal_path)
        # Add cache headers to avoid repeated ZIP extraction (cache for 5 minutes)
        cache_headers = {"Cache-Control": "private, max-age=300"}
        if mime_type and mime_type.startswith("text/"):
            return PlainTextResponse(content=content.decode("utf-8"), media_type=mime_type, headers=cache_headers)

        # Default to plain text for unknown types that look like text
        try:
            return PlainTextResponse(content=content.decode("utf-8"), media_type="text/plain", headers=cache_headers)
        except UnicodeDecodeError:
            return Response(content=content, media_type=mime_type or "application/octet-stream", headers=cache_headers)

    actual_path = resolve_thread_virtual_path(thread_id, path)

    logger.info(f"Resolving artifact path: thread_id={thread_id}, requested_path={path}, actual_path={actual_path}")

    if not actual_path.exists():
        raise HTTPException(status_code=404, detail=f"Artifact not found: {path}")

    if not actual_path.is_file():
        raise HTTPException(status_code=400, detail=f"Path is not a file: {path}")

    mime_type, _ = mimetypes.guess_type(actual_path)

    # Encode filename for Content-Disposition header (RFC 5987)
    encoded_filename = quote(actual_path.name)

    # if `download` query parameter is true, return the file as a download
    if request.query_params.get("download"):
        return FileResponse(path=actual_path, filename=actual_path.name, media_type=mime_type, headers={"Content-Disposition": f"attachment; filename*=UTF-8''{encoded_filename}"})

    if mime_type and mime_type == "text/html":
        content = await asyncio.to_thread(actual_path.read_text)
        # Serve HTML artifacts in a sandboxed iframe context to prevent XSS
        return HTMLResponse(
            content=content,
            headers={
                "Content-Security-Policy": "default-src 'self'; script-src 'none'; style-src 'self' 'unsafe-inline'",
                "X-Content-Type-Options": "nosniff",
                "X-Frame-Options": "SAMEORIGIN",
            },
        )

    if mime_type and mime_type.startswith("text/"):
        content = await asyncio.to_thread(actual_path.read_text)
        return PlainTextResponse(content=content, media_type=mime_type)

    if is_text_file_by_content(actual_path):
        content = await asyncio.to_thread(actual_path.read_text)
        return PlainTextResponse(content=content, media_type=mime_type)

    raw = await asyncio.to_thread(actual_path.read_bytes)
    return Response(content=raw, media_type=mime_type, headers={"Content-Disposition": f"inline; filename*=UTF-8''{encoded_filename}"})


@router.delete(
    "/threads/{thread_id}/artifacts/{path:path}",
    summary="Delete Artifact File",
    description="Delete an artifact file generated by the AI agent from the thread workspace.",
)
async def delete_artifact(thread_id: str, path: str) -> dict:
    """Delete a single artifact file by its virtual path.

    Args:
        thread_id: The thread ID.
        path: The artifact path with virtual prefix (e.g., mnt/user-data/outputs/file.txt).

    Returns:
        ``{"success": True, "path": <path>}`` on success.

    Raises:
        HTTPException:
            - 400 if path is invalid or not a regular file.
            - 403 if access denied (path traversal detected).
            - 404 if file not found.
            - 500 if the underlying unlink fails.
    """
    actual_path = resolve_thread_virtual_path(thread_id, path)
    logger.info("Deleting artifact: thread_id=%s, requested_path=%s, actual_path=%s", thread_id, path, actual_path)

    if not actual_path.exists():
        raise HTTPException(status_code=404, detail=f"Artifact not found: {path}")
    if not actual_path.is_file():
        raise HTTPException(status_code=400, detail=f"Path is not a file: {path}")

    try:
        await asyncio.to_thread(actual_path.unlink)
    except PermissionError as exc:
        logger.warning("Permission denied deleting artifact %s: %s", actual_path, exc)
        raise HTTPException(status_code=403, detail="Permission denied") from exc
    except OSError as exc:
        logger.error("Failed to delete artifact %s: %s", actual_path, exc)
        raise HTTPException(status_code=500, detail="Failed to delete artifact") from exc

    # Remove the deleted path from the thread's artifacts list in LangGraph state
    # so that on refresh the file no longer appears in the file panel.
    try:
        from langgraph_sdk import get_client

        from src.agents.thread_state import ARTIFACTS_REPLACE_SENTINEL
        _base_url = os.getenv("OCTO_LANGGRAPH_BASE_URL", "http://localhost:19804")
        _client = get_client(url=_base_url)
        _state = await _client.threads.get_state(thread_id)
        _artifacts: list[str] = list((_state.get("values") or {}).get("artifacts") or [])
        # The stored path may have a leading '/' while the API path param may not
        _normalized = "/" + path.lstrip("/")
        if _normalized in _artifacts or path in _artifacts:
            _artifacts = [a for a in _artifacts if a != _normalized and a != path]
            # The artifacts channel uses an additive (union) reducer, so a plain
            # list update would be merged back with the existing entries and the
            # deleted path would reappear in the file panel. Prefix the replace
            # sentinel so the reducer performs authoritative replace semantics.
            await _client.threads.update_state(
                thread_id,
                {"artifacts": [ARTIFACTS_REPLACE_SENTINEL, *_artifacts]},
            )
            logger.info(
                "delete_artifact: removed %s from thread state artifacts (thread=%s)",
                _normalized, thread_id,
            )
    except Exception as _exc:
        # Non-fatal: the file is already deleted; state cleanup is best-effort.
        # ConflictError means a run is in-flight; it will write its own artifacts
        # update on completion, so we don't need to do anything here.
        _exc_name = type(_exc).__name__
        if "Conflict" in _exc_name:
            logger.debug(
                "delete_artifact: thread=%s has in-flight run, skipping state update (file deleted)",
                thread_id,
            )
        else:
            logger.warning(
                "delete_artifact: could not update thread state artifacts for thread=%s: %s",
                thread_id, _exc,
            )

    return {"success": True, "path": path}

