"""Enhanced Prometheus metrics for octoagent business domains.

Adds tool call tracking, LLM token consumption, workspace lifecycle,
and skill evolution quality metrics.
"""

import logging
from typing import Any, Optional

logger = logging.getLogger(__name__)

# Metric counters (would be registered in the monitoring module)
METRIC_CATEGORIES = {
    "tool_calls": "octoagent_tool_calls_total",
    "llm_tokens": "octoagent_llm_tokens_total",
    "workspace_lifecycle": "octoagent_workspace_lifecycle_duration_seconds",
    "skill_evolution": "octoagent_skill_evolution_quality_score",
}


def register_business_metrics(registry: Any) -> None:
    """Register additional business-domain metrics with the registry.

    Args:
        registry: The metrics registry to add counters/gauges/histograms to.
    """
    try:
        # Tool calls by tool name
        if hasattr(registry, "Counter"):
            registry._tool_calls = registry.Counter(
                METRIC_CATEGORIES["tool_calls"],
                "Total number of tool calls by tool name",
                ["tool_name"],
            )
        
        # LLM token consumption
        if hasattr(registry, "Counter"):
            registry._llm_tokens_input = registry.Counter(
                f"{METRIC_CATEGORIES['llm_tokens']}_input",
                "Total input tokens consumed by LLM",
                ["model"],
            )
            registry._llm_tokens_output = registry.Counter(
                f"{METRIC_CATEGORIES['llm_tokens']}_output",
                "Total output tokens generated by LLM",
                ["model"],
            )
        
        # Workspace lifecycle duration
        if hasattr(registry, "Histogram"):
            registry._workspace_lifecycle = registry.Histogram(
                METRIC_CATEGORIES["workspace_lifecycle"],
                "Workspace creation to completion duration in seconds",
                buckets=[60, 300, 900, 1800, 3600, 7200, 14400],
            )
        
        # Skill evolution quality score
        if hasattr(registry, "Gauge"):
            registry._skill_evolution_quality = registry.Gauge(
                METRIC_CATEGORIES["skill_evolution"],
                "Latest skill evolution quality score (0-10)",
            )
        
        logger.info("Registered %d business-domain metrics", len(METRIC_CATEGORIES))
        
    except Exception as e:  # noqa: BLE001
        logger.error("Failed to register business metrics: %s", str(e))


def increment_tool_calls(tool_name: str) -> None:
    """Increment the tool calls counter for a specific tool.

    Args:
        tool_name: The name of the tool that was called.
    """
    try:
        from src.gateway.monitoring import get_metrics_registry
        registry = get_metrics_registry()
        if hasattr(registry, "_tool_calls"):
            registry._tool_calls.labels(tool_name=tool_name).inc()
    except Exception as e:  # noqa: BLE001
        logger.debug("Failed to increment tool calls metric: %s", str(e))


def record_llm_tokens(model: str, input_tokens: int, output_tokens: int) -> None:
    """Record LLM token consumption for a model.

    Args:
        model: The model name.
        input_tokens: Number of input tokens.
        output_tokens: Number of output tokens.
    """
    try:
        from src.gateway.monitoring import get_metrics_registry
        registry = get_metrics_registry()
        if hasattr(registry, "_llm_tokens_input"):
            registry._llm_tokens_input.labels(model=model).inc(input_tokens)
        if hasattr(registry, "_llm_tokens_output"):
            registry._llm_tokens_output.labels(model=model).inc(output_tokens)
    except Exception as e:  # noqa: BLE001
        logger.debug("Failed to record LLM tokens metric: %s", str(e))


def complete_workspace_lifecycle(duration_seconds: float) -> None:
    """Record a workspace lifecycle completion.

    Args:
        duration_seconds: The time from workspace creation to completion.
    """
    try:
        from src.gateway.monitoring import get_metrics_registry
        registry = get_metrics_registry()
        if hasattr(registry, "_workspace_lifecycle"):
            registry._workspace_lifecycle.observe(duration_seconds)
    except Exception as e:  # noqa: BLE001
        logger.debug("Failed to record workspace lifecycle metric: %s", str(e))


def update_skill_evolution_quality(score: float) -> None:
    """Update the skill evolution quality score gauge.

    Args:
        score: The quality score (typically 0-10).
    """
    try:
        from src.gateway.monitoring import get_metrics_registry
        registry = get_metrics_registry()
        if hasattr(registry, "_skill_evolution_quality"):
            registry._skill_evolution_quality.set(score)
    except Exception as e:  # noqa: BLE001
        logger.debug("Failed to update skill evolution quality metric: %s", str(e))